import type { NextPage } from 'next';
import Head from 'next/head';
import { Main } from '@components/Layout/Main';

const GetQuote: NextPage = () => {
  return (
    <div>
      <Head>
        <title>GET TUOTEUOWTUO</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Main>
        <div>GELLLLWGSDA</div>
      </Main>
    </div>
  );
};

export default GetQuote;
